### PR TITLE
Added colors, less classes

### PR DESCRIPTION
**Pull request by eqMFqfFd**

### CODE REVIEW

**Review by Awzaw — COMMENTED** [review]
Ok for adding colour, but why remove those 'use' statements?!

**Comment by eqMFqfFd** [comment]
@Awzaw I've removed two `use` statements and replaced them with full path `\pocketmine\event\player\PlayerInteractEvent`.
It looks a bit ugly

**Comment by Awzaw** [comment]
I see that's what you've done, but why do it?

**Comment by eqMFqfFd** [comment]
@Awzaw The code looks ugly including so many *classes* put together. And as they are mentioned once.
#
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by SOF3** [comment]
The point of use statements is not to minimize the number of bytes in the code. It is to put all the long mess together at the beginning so that you don't have to see the mess in the real code body.

**Comment by eqMFqfFd** [comment]
@SOF3  that can be removed if wanted.

**Comment by SOF3** [comment]
Closed until aforementioned issues resolved.

**Pull request closed without merging**
